description: A brief description of the project
name: cloudsecnext25_at_night
origin:
  generated: true
  template:
    branch: main
    commit hash: 5dd9e2237ce22c8b6b79a20ae6079210e315d2ae
    cookiecutter:
      _checkout: null
      _repo_dir: /Users/jonzeolla/.cookiecutters/ai-native-python
      _template: gh:zenable-io/ai-native-python
      company_domain: jonzeolla.com
      company_name: jonzeolla
      dockerhub: 'yes'
      github_org: jonzeolla
      license: MIT
      project_name: cloudsecnext25-at-night
      project_owner_github_username: jonzeolla
      project_short_description: A brief description of the project
      project_slug: cloudsecnext25_at_night
      public: 'yes'
      python_version: '3.13'
    dirty: false
    location: https://github.com/zenable-io/ai-native-python.git
  timestamp: '2025-10-07T18:27:44+00:00'
